### PR TITLE
feat: add deployment resource

### PR DESCRIPTION
**Pull request by mcruzdev**
This pull request aims to solve the #2 issue.

By default we are using `daemonset` and if the user wants to use as deployment then should be use `--set ambient.strategy=deployment` on helm install step.

The deployment strategy by default is using 1 replicas.

### CODE REVIEW

**Comment by mcruzdev** [comment]
Hello @salaboy, what do you think about `ambient.useAsDeployment` by default this value must be `false` because the default is daemonset.

**Comment by salaboy** [comment]
@mcruzdev let's use something like `ambient.strategy` where we can set value "daemonset" or "deployment", let's not use a boolean for that

**Comment by salaboy** [comment]
@mcruzdev how is this going?

**Comment by mcruzdev** [comment]
> @mcruzdev how is this going?

I am trying to use with daemonset first.

**Review by salaboy — CHANGES_REQUESTED** [review]
@mcruzdev this is a great start.. I requested some changes.. but overall this looks good.

**Comment by mcruzdev** [comment]
Hi @salaboy, I created a file shared file containing shared spec... what do you thing? I do not know if it is a common approach when working with helm templates.

**Comment by salaboy** [comment]
@mcruzdev interesting.. I don't know why I don't like it exactly, which means it should be fine for now.. 
Looking at the changes, it looks ready to be merged. Any more things that you want to add to this PR before I merge it?

**Review by salaboy — APPROVED** [review]

**Pull request merged**
