### PR TITLE
Add unit tests to service and daemonset resources

### PR DESCRIPTION
**Pull request by mcruzdev**
This pull request adds an initial test suite for testing the helm chart. 
As discussed in #3 issue we initially are using [helm-unittest](https://github.com/quintush/helm-unittest) tolling.

In addition, was added a workflow to check the helm in each commit.

### CODE REVIEW

**Comment by salaboy** [comment]
@mcruzdev this looks good.. can you add tests for the DaemonSet resource? that is the main thing that we should check until we add the option for having a Deployment.

**Comment by mcruzdev** [comment]
Hi @salaboy,
I have some notes here:

1. Two fields are required but do not exist on `values.yaml` file.

```yaml
ambient:
  appId: appId
  proxy:
    remoteURL: https://local
```

2. There are some fields referenced on templates but not inside `values.yaml`, like:

```yaml
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
```

**Comment by salaboy** [comment]
@mcruzdev that's great.. good time to clean things up.. so if it is not in the charts.. there is no need to have them in the values.yaml file

**Comment by salaboy** [comment]
@mcruzdev let me know when things are ready for review

**Comment by mcruzdev** [comment]
@salaboy if is not necessary to change the `Chart` and the `values.yml`, let's review! 😄

**Comment by mcruzdev** [comment]
> @mcruzdev that's great.. good time to clean things up.. so if it is not in the charts.. there is no need to have them in the values.yaml file

I will make a double check!

**Comment by mcruzdev** [comment]
Hi @salaboy, the PR is ok to review!

**Comment by salaboy** [comment]
@mcruzdev I am happy with this first iteration, let me merge this.. so you can work on this: https://github.com/dapr-sandbox/dapr-ambient/issues/2

**Pull request merged**
